version: '3'

services:
  api-contact:
    image: bitnami/postgresql
    ports:
      - 5433:5433
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apicontact